controller_manager:
  ros__parameters:
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - Base_base
      - Base_hombro
      - Hombro_medio
      - UNION_MUNECA
      - muneca_pinza
      - pinza_final